# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
